### PR TITLE
Move the postmessage logic from the html directive to the module run blocK.

### PR DESCRIPTION
**Pull request by veewee**
This commit will solve issue #5.
Tests are still passing and are still valid in my opinion.
It breaks BC because the code is moved to the run block instead of using the html directive.

### CODE REVIEW

**Comment by veewee** [comment]
Looks like travis has invalid credentials. Can you take a look at it?

**Comment by kylewelsby** [comment]
Yes the sauce labs keys are encrypted and it appears pull requests are not including the variables.  I have pulled your code and checked locally and tests pass OK.

**Comment by veewee** [comment]
OK. Thanks!
Can you also create a new tag for this version? Would like to use it in a project I am working on.

**Comment by kylewelsby** [comment]
Oops, forgot about that, thanks. https://github.com/kylewelsby/angular-post-message/releases/tag/v1.3.0

**Comment by veewee** [comment]
Great! Thanks mate!

**Pull request merged**
